<a href="https://colab.research.google.com/github/dilshanwickramasinghe007-lab/Fake-News-Detection-Project-Using-Machine-Learning/blob/main/Fake_News_Detection.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np
import pandas as pd

In [4]:
true = pd.read_csv('/content/sample_data/True.csv')

In [5]:
fake = pd.read_csv('/content/sample_data/Fake.csv')

In [6]:
true.head()

,title,text,subject,date
0,"As U.S. budget fight looms, Republicans flip t...",WASHINGTON (Reuters) - The head of a conservat...,politicsNews,"December 31, 2017"
1,U.S. military to accept transgender recruits o...,WASHINGTON (Reuters) - Transgender people will...,politicsNews,"December 29, 2017"
2,Senior U.S. Republican senator: 'Let Mr. Muell...,WASHINGTON (Reuters) - The special counsel inv...,politicsNews,"December 31, 2017"
3,FBI Russia probe helped by Australian diplomat...,WASHINGTON (Reuters) - Trump campaign adviser ...,politicsNews,"December 30, 2017"
4,Trump wants Postal Service to charge 'much mor...,SEATTLE/WASHINGTON (Reuters) - President Donal...,politicsNews,"December 29, 2017"

In [7]:
fake.head()

,title,text,subject,date
0,Donald Trump Sends Out Embarrassing New Year’...,Donald Trump just couldn t wish all Americans ...,News,"December 31, 2017"
1,Drunk Bragging Trump Staffer Started Russian ...,House Intelligence Committee Chairman Devin Nu...,News,"December 31, 2017"
2,Sheriff David Clarke Becomes An Internet Joke...,"On Friday, it was revealed that former Milwauk...",News,"December 30, 2017"
3,Trump Is So Obsessed He Even Has Obama’s Name...,"On Christmas day, Donald Trump announced that ...",News,"December 29, 2017"
4,Pope Francis Just Called Out Donald Trump Dur...,Pope Francis used his annual Christmas Day mes...,News,"December 25, 2017"

In [8]:
true['label'] = 1

In [9]:
fake['label'] = 0

In [10]:
true.head()

,title,text,subject,date,label
0,"As U.S. budget fight looms, Republicans flip t...",WASHINGTON (Reuters) - The head of a conservat...,politicsNews,"December 31, 2017",1
1,U.S. military to accept transgender recruits o...,WASHINGTON (Reuters) - Transgender people will...,politicsNews,"December 29, 2017",1
2,Senior U.S. Republican senator: 'Let Mr. Muell...,WASHINGTON (Reuters) - The special counsel inv...,politicsNews,"December 31, 2017",1
3,FBI Russia probe helped by Australian diplomat...,WASHINGTON (Reuters) - Trump campaign adviser ...,politicsNews,"December 30, 2017",1
4,Trump wants Postal Service to charge 'much mor...,SEATTLE/WASHINGTON (Reuters) - President Donal...,politicsNews,"December 29, 2017",1

In [11]:
news = pd.concat([fake, true], axis = 0)

In [12]:
news.head()

,title,text,subject,date,label
0,Donald Trump Sends Out Embarrassing New Year’...,Donald Trump just couldn t wish all Americans ...,News,"December 31, 2017",0
1,Drunk Bragging Trump Staffer Started Russian ...,House Intelligence Committee Chairman Devin Nu...,News,"December 31, 2017",0
2,Sheriff David Clarke Becomes An Internet Joke...,"On Friday, it was revealed that former Milwauk...",News,"December 30, 2017",0
3,Trump Is So Obsessed He Even Has Obama’s Name...,"On Christmas day, Donald Trump announced that ...",News,"December 29, 2017",0
4,Pope Francis Just Called Out Donald Trump Dur...,Pope Francis used his annual Christmas Day mes...,News,"December 25, 2017",0

In [13]:
news.isnull().sum()

title      0
text       0
subject    0
date       0
label      0
dtype: int64

In [14]:
news = news.drop(['title', 'subject','date'], axis = 1)

In [15]:
news.head()

                                                text  label
0  Donald Trump just couldn t wish all Americans ...      0
1  House Intelligence Committee Chairman Devin Nu...      0
2  On Friday, it was revealed that former Milwauk...      0
3  On Christmas day, Donald Trump announced that ...      0
4  Pope Francis used his annual Christmas Day mes...      0

In [16]:
news = news.sample(frac = 1)        #Reshuffling

In [17]:
news.head()

                                                    text  label
18596  The White House confirmed to FOX Business that...      0
8153   Donald Trump supporters have taken it upon the...      0
22493  Tune in to the Alternate Current Radio Network...      0
6490   PARIS (Reuters) - Nissan is halting joint deve...      1
11626        https://www.youtube.com/watch?v=uCS4RB9G13M      0

In [22]:
news = pd.concat([fake, true], axis = 0)
news = news.drop(['title', 'subject','date'], axis = 1)
news = news.sample(frac = 1)
news.reset_index(inplace = True)
news.head()

   index                                               text  label
0   2499  PHILADELPHIA (Reuters) - The mayor of Allentow...      1
1    961  Former Attorney General Eric Holder, who serve...      0
2  15959  What will he think of next? Is Kim Jong-un is ...      0
3    517  SACRAMENTO, Calif. (Reuters) - California lawm...      1
4   2253  WASHINGTON (Reuters) - President Donald Trump’...      1

In [23]:
news.drop(['index'], axis = 1, inplace = True)

In [24]:
news.head()

                                                text  label
0  PHILADELPHIA (Reuters) - The mayor of Allentow...      1
1  Former Attorney General Eric Holder, who serve...      0
2  What will he think of next? Is Kim Jong-un is ...      0
3  SACRAMENTO, Calif. (Reuters) - California lawm...      1
4  WASHINGTON (Reuters) - President Donald Trump’...      1

In [25]:
import re

In [27]:
def wordopt(text):
#convert into lowercase
  text = text.lower()
#remove URLs
  text = re.sub(r'https/://\S+|www\.\S+', '', text )
#remove HTML tags
  text = re.sub(r'<,*?>','', text)
#remove punctuation
  text = re.sub(r'[^\w\s]','', text)
#remove digits
  text = re.sub(r'\d','', text)
#remove newline characters
  text = re.sub(r'\n', '', text)
  return text

In [28]:
news['text'] = news['text'].apply(wordopt)

In [29]:
news['text']

0        philadelphia reuters  the mayor of allentown t...
1        former attorney general eric holder who served...
2        what will he think of next is kim jongun is pr...
3        sacramento calif reuters  california lawmaker ...
4        washington reuters  president donald trumps vo...
                               ...
44893     the times asserts that such censorship would ...
44894    washington reuters  us democratic lawmakers ca...
44895    buenos aires reuters  us president barack obam...
44896    but is threatening trump on social media consi...
44897    washington reuters  former central intelligenc...
Name: text, Length: 44898, dtype: object

In [30]:
x = news['text']
y = news['label']

In [31]:
x

0        philadelphia reuters  the mayor of allentown t...
1        former attorney general eric holder who served...
2        what will he think of next is kim jongun is pr...
3        sacramento calif reuters  california lawmaker ...
4        washington reuters  president donald trumps vo...
                               ...
44893     the times asserts that such censorship would ...
44894    washington reuters  us democratic lawmakers ca...
44895    buenos aires reuters  us president barack obam...
44896    but is threatening trump on social media consi...
44897    washington reuters  former central intelligenc...
Name: text, Length: 44898, dtype: object

In [32]:
y

0        1
1        0
2        0
3        1
4        1
        ..
44893    0
44894    1
44895    1
44896    0
44897    1
Name: label, Length: 44898, dtype: int64

In [33]:
from sklearn.model_selection import train_test_split

In [34]:
x_train, x_test, y_train, y_test = train_test_split(x,y,test_size=0.3)

In [35]:
x_train.shape

(31428,)

In [36]:
x_test.shape

(13470,)

In [38]:
from sklearn.feature_extraction.text import TfidfVectorizer

In [40]:
Vectorization = TfidfVectorizer()

In [42]:
xv_train = Vectorization.fit_transform(x_train)

In [44]:
xv_test = Vectorization.transform(x_test)

In [45]:
xv_train

<Compressed Sparse Row sparse matrix of dtype 'float64'
	with 6450625 stored elements and shape (31428, 177202)>

In [46]:
xv_test

<Compressed Sparse Row sparse matrix of dtype 'float64'
	with 2733302 stored elements and shape (13470, 177202)>

In [48]:
from sklearn.linear_model import LogisticRegression

In [49]:
LR = LogisticRegression()

In [50]:
LR.fit(xv_train, y_train)

LogisticRegression()

In [51]:
pred_lr = LR.predict(xv_test)

In [52]:
LR.score(xv_test, y_test)

0.9893095768374165

In [54]:
from sklearn.metrics import classification_report
print(classification_report(y_test, pred_lr))

              precision    recall  f1-score   support

           0       0.99      0.99      0.99      7049
           1       0.99      0.99      0.99      6421

    accuracy                           0.99     13470
   macro avg       0.99      0.99      0.99     13470
weighted avg       0.99      0.99      0.99     13470

In [55]:
from sklearn.tree import DecisionTreeClassifier

In [56]:
DTC = DecisionTreeClassifier()

In [57]:
DTC.fit(xv_train,y_train)

DecisionTreeClassifier()

In [58]:
pred_dtc = DTC.predict(xv_test)

In [59]:
DTC.score(xv_test, y_test)

0.9955456570155902

In [60]:
print(classification_report(y_test, pred_dtc))

              precision    recall  f1-score   support

           0       1.00      1.00      1.00      7049
           1       1.00      1.00      1.00      6421

    accuracy                           1.00     13470
   macro avg       1.00      1.00      1.00     13470
weighted avg       1.00      1.00      1.00     13470

In [62]:
from sklearn.ensemble import RandomForestClassifier

In [63]:
rfc = RandomForestClassifier()

In [64]:
rfc.fit(xv_train, y_train)

RandomForestClassifier()

In [65]:
pred_rfc = rfc.predict(xv_test)

In [66]:
rfc.score(xv_test, y_test)

0.9876763177431329

In [67]:
print(classification_report(y_test, pred_rfc))

              precision    recall  f1-score   support

           0       0.99      0.99      0.99      7049
           1       0.99      0.99      0.99      6421

    accuracy                           0.99     13470
   macro avg       0.99      0.99      0.99     13470
weighted avg       0.99      0.99      0.99     13470

In [69]:
from sklearn.ensemble import GradientBoostingClassifier

In [70]:
gbc = GradientBoostingClassifier()

In [71]:
gbc.fit(xv_train, y_train)

GradientBoostingClassifier()

In [72]:
pred_gbc = gbc.predict(xv_test)

In [73]:
gbc.score(xv_test, y_test)

0.9959910913140312

In [74]:
print(classification_report(y_test, pred_gbc))

              precision    recall  f1-score   support

           0       1.00      0.99      1.00      7049
           1       0.99      1.00      1.00      6421

    accuracy                           1.00     13470
   macro avg       1.00      1.00      1.00     13470
weighted avg       1.00      1.00      1.00     13470

In [75]:
def output_lable(n):
    if n == 0:
        return "Fake News"
    elif n == 1:
        return "Not A Fake News"

In [76]:
def manual_testing(news):
    testing_news = {"text":[news]}
    new_def_test = pd.DataFrame(testing_news)
    new_def_test["text"] = new_def_test["text"].apply(wordopt)
    new_x_test = new_def_test["text"]
    new_xv_test = Vectorization.transform(new_x_test)
    pred_lr = LR.predict(new_xv_test)
    pred_gbc = gbc.predict(new_xv_test)
    pred_rfc = rfc.predict(new_xv_test)
    return "\n\nLR Prediction: {} \nGBC Prediction: {} \nRFC Prediction: {}".format(
        output_lable(pred_lr[0]),
        output_lable(pred_gbc[0]),
        output_lable(pred_rfc[0])
    )

In [78]:
news_article = str(input())

Trump Said Some INSANELY Racist Stuff Inside The Oval Office, And Witnesses Back It Up"

In [79]:
manual_testing(news_article)

'\n\nLR Prediction: Fake News \nGBC Prediction: Fake News \nRFC Prediction: Fake News'